-- County Quizzer Database Schema and Data
-- Run this script to create and populate the SQLite database

-- Create States table
CREATE TABLE IF NOT EXISTS states (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,
    county_count INTEGER NOT NULL
);

-- Create Counties table
CREATE TABLE IF NOT EXISTS counties (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    state_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (state_id) REFERENCES states(id)
);

-- Insert states data
INSERT INTO states (name, county_count) VALUES
('Test', 4),
('Oregon', 36),
('Washington', 39),
('California', 58),
('Texas', 50),
('Florida', 25),
('New York', 30);

-- Insert Test state counties
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'Test'), 'one'),
((SELECT id FROM states WHERE name = 'Test'), 'two'),
((SELECT id FROM states WHERE name = 'Test'), 'three'),
((SELECT id FROM states WHERE name = 'Test'), 'four');

-- Insert Oregon counties
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'Oregon'), 'Baker'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Benton'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Clackamas'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Clatsop'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Columbia'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Coos'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Crook'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Curry'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Deschutes'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Douglas'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Gilliam'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Grant'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Harney'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Hood River'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Jackson'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Jefferson'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Josephine'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Klamath'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Lake'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Lane'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Lincoln'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Linn'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Malheur'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Marion'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Morrow'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Multnomah'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Polk'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Sherman'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Tillamook'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Umatilla'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Union'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Wallowa'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Wasco'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Washington'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Wheeler'),
((SELECT id FROM states WHERE name = 'Oregon'), 'Yamhill');

-- Insert Washington counties
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'Washington'), 'Adams'),
((SELECT id FROM states WHERE name = 'Washington'), 'Asotin'),
((SELECT id FROM states WHERE name = 'Washington'), 'Benton'),
((SELECT id FROM states WHERE name = 'Washington'), 'Chelan'),
((SELECT id FROM states WHERE name = 'Washington'), 'Clallam'),
((SELECT id FROM states WHERE name = 'Washington'), 'Clark'),
((SELECT id FROM states WHERE name = 'Washington'), 'Columbia'),
((SELECT id FROM states WHERE name = 'Washington'), 'Cowlitz'),
((SELECT id FROM states WHERE name = 'Washington'), 'Douglas'),
((SELECT id FROM states WHERE name = 'Washington'), 'Ferry'),
((SELECT id FROM states WHERE name = 'Washington'), 'Franklin'),
((SELECT id FROM states WHERE name = 'Washington'), 'Garfield'),
((SELECT id FROM states WHERE name = 'Washington'), 'Grant'),
((SELECT id FROM states WHERE name = 'Washington'), 'Grays Harbor'),
((SELECT id FROM states WHERE name = 'Washington'), 'Island'),
((SELECT id FROM states WHERE name = 'Washington'), 'Jefferson'),
((SELECT id FROM states WHERE name = 'Washington'), 'King'),
((SELECT id FROM states WHERE name = 'Washington'), 'Kitsap'),
((SELECT id FROM states WHERE name = 'Washington'), 'Kittitas'),
((SELECT id FROM states WHERE name = 'Washington'), 'Klickitat'),
((SELECT id FROM states WHERE name = 'Washington'), 'Lewis'),
((SELECT id FROM states WHERE name = 'Washington'), 'Lincoln'),
((SELECT id FROM states WHERE name = 'Washington'), 'Mason'),
((SELECT id FROM states WHERE name = 'Washington'), 'Okanogan'),
((SELECT id FROM states WHERE name = 'Washington'), 'Pacific'),
((SELECT id FROM states WHERE name = 'Washington'), 'Pend Oreille'),
((SELECT id FROM states WHERE name = 'Washington'), 'Pierce'),
((SELECT id FROM states WHERE name = 'Washington'), 'San Juan'),
((SELECT id FROM states WHERE name = 'Washington'), 'Skagit'),
((SELECT id FROM states WHERE name = 'Washington'), 'Skamania'),
((SELECT id FROM states WHERE name = 'Washington'), 'Snohomish'),
((SELECT id FROM states WHERE name = 'Washington'), 'Spokane'),
((SELECT id FROM states WHERE name = 'Washington'), 'Stevens'),
((SELECT id FROM states WHERE name = 'Washington'), 'Thurston'),
((SELECT id FROM states WHERE name = 'Washington'), 'Wahkiakum'),
((SELECT id FROM states WHERE name = 'Washington'), 'Walla Walla'),
((SELECT id FROM states WHERE name = 'Washington'), 'Whatcom'),
((SELECT id FROM states WHERE name = 'Washington'), 'Whitman'),
((SELECT id FROM states WHERE name = 'Washington'), 'Yakima');

-- Insert California counties
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'California'), 'Alameda'),
((SELECT id FROM states WHERE name = 'California'), 'Alpine'),
((SELECT id FROM states WHERE name = 'California'), 'Amador'),
((SELECT id FROM states WHERE name = 'California'), 'Butte'),
((SELECT id FROM states WHERE name = 'California'), 'Calaveras'),
((SELECT id FROM states WHERE name = 'California'), 'Colusa'),
((SELECT id FROM states WHERE name = 'California'), 'Contra Costa'),
((SELECT id FROM states WHERE name = 'California'), 'Del Norte'),
((SELECT id FROM states WHERE name = 'California'), 'El Dorado'),
((SELECT id FROM states WHERE name = 'California'), 'Fresno'),
((SELECT id FROM states WHERE name = 'California'), 'Glenn'),
((SELECT id FROM states WHERE name = 'California'), 'Humboldt'),
((SELECT id FROM states WHERE name = 'California'), 'Imperial'),
((SELECT id FROM states WHERE name = 'California'), 'Inyo'),
((SELECT id FROM states WHERE name = 'California'), 'Kern'),
((SELECT id FROM states WHERE name = 'California'), 'Kings'),
((SELECT id FROM states WHERE name = 'California'), 'Lake'),
((SELECT id FROM states WHERE name = 'California'), 'Lassen'),
((SELECT id FROM states WHERE name = 'California'), 'Los Angeles'),
((SELECT id FROM states WHERE name = 'California'), 'Madera'),
((SELECT id FROM states WHERE name = 'California'), 'Marin'),
((SELECT id FROM states WHERE name = 'California'), 'Mariposa'),
((SELECT id FROM states WHERE name = 'California'), 'Mendocino'),
((SELECT id FROM states WHERE name = 'California'), 'Merced'),
((SELECT id FROM states WHERE name = 'California'), 'Modoc'),
((SELECT id FROM states WHERE name = 'California'), 'Mono'),
((SELECT id FROM states WHERE name = 'California'), 'Monterey'),
((SELECT id FROM states WHERE name = 'California'), 'Napa'),
((SELECT id FROM states WHERE name = 'California'), 'Nevada'),
((SELECT id FROM states WHERE name = 'California'), 'Orange'),
((SELECT id FROM states WHERE name = 'California'), 'Placer'),
((SELECT id FROM states WHERE name = 'California'), 'Plumas'),
((SELECT id FROM states WHERE name = 'California'), 'Riverside'),
((SELECT id FROM states WHERE name = 'California'), 'Sacramento'),
((SELECT id FROM states WHERE name = 'California'), 'San Benito'),
((SELECT id FROM states WHERE name = 'California'), 'San Bernardino'),
((SELECT id FROM states WHERE name = 'California'), 'San Diego'),
((SELECT id FROM states WHERE name = 'California'), 'San Francisco'),
((SELECT id FROM states WHERE name = 'California'), 'San Joaquin'),
((SELECT id FROM states WHERE name = 'California'), 'San Luis Obispo'),
((SELECT id FROM states WHERE name = 'California'), 'San Mateo'),
((SELECT id FROM states WHERE name = 'California'), 'Santa Barbara'),
((SELECT id FROM states WHERE name = 'California'), 'Santa Clara'),
((SELECT id FROM states WHERE name = 'California'), 'Santa Cruz'),
((SELECT id FROM states WHERE name = 'California'), 'Shasta'),
((SELECT id FROM states WHERE name = 'California'), 'Sierra'),
((SELECT id FROM states WHERE name = 'California'), 'Siskiyou'),
((SELECT id FROM states WHERE name = 'California'), 'Solano'),
((SELECT id FROM states WHERE name = 'California'), 'Sonoma'),
((SELECT id FROM states WHERE name = 'California'), 'Stanislaus'),
((SELECT id FROM states WHERE name = 'California'), 'Sutter'),
((SELECT id FROM states WHERE name = 'California'), 'Tehama'),
((SELECT id FROM states WHERE name = 'California'), 'Trinity'),
((SELECT id FROM states WHERE name = 'California'), 'Tulare'),
((SELECT id FROM states WHERE name = 'California'), 'Tuolumne'),
((SELECT id FROM states WHERE name = 'California'), 'Ventura'),
((SELECT id FROM states WHERE name = 'California'), 'Yolo'),
((SELECT id FROM states WHERE name = 'California'), 'Yuba');

-- Insert Texas counties (subset)
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'Texas'), 'Harris'),
((SELECT id FROM states WHERE name = 'Texas'), 'Dallas'),
((SELECT id FROM states WHERE name = 'Texas'), 'Tarrant'),
((SELECT id FROM states WHERE name = 'Texas'), 'Bexar'),
((SELECT id FROM states WHERE name = 'Texas'), 'Travis'),
((SELECT id FROM states WHERE name = 'Texas'), 'Collin'),
((SELECT id FROM states WHERE name = 'Texas'), 'Denton'),
((SELECT id FROM states WHERE name = 'Texas'), 'Fort Bend'),
((SELECT id FROM states WHERE name = 'Texas'), 'Hidalgo'),
((SELECT id FROM states WHERE name = 'Texas'), 'El Paso'),
((SELECT id FROM states WHERE name = 'Texas'), 'Williamson'),
((SELECT id FROM states WHERE name = 'Texas'), 'Montgomery'),
((SELECT id FROM states WHERE name = 'Texas'), 'Galveston'),
((SELECT id FROM states WHERE name = 'Texas'), 'Brazoria'),
((SELECT id FROM states WHERE name = 'Texas'), 'Jefferson'),
((SELECT id FROM states WHERE name = 'Texas'), 'Nueces'),
((SELECT id FROM states WHERE name = 'Texas'), 'Bell'),
((SELECT id FROM states WHERE name = 'Texas'), 'Cameron'),
((SELECT id FROM states WHERE name = 'Texas'), 'Brazos'),
((SELECT id FROM states WHERE name = 'Texas'), 'Hays'),
((SELECT id FROM states WHERE name = 'Texas'), 'McLennan'),
((SELECT id FROM states WHERE name = 'Texas'), 'Guadalupe'),
((SELECT id FROM states WHERE name = 'Texas'), 'Ellis'),
((SELECT id FROM states WHERE name = 'Texas'), 'Johnson'),
((SELECT id FROM states WHERE name = 'Texas'), 'Kaufman'),
((SELECT id FROM states WHERE name = 'Texas'), 'Parker'),
((SELECT id FROM states WHERE name = 'Texas'), 'Rockwall'),
((SELECT id FROM states WHERE name = 'Texas'), 'Smith'),
((SELECT id FROM states WHERE name = 'Texas'), 'Webb'),
((SELECT id FROM states WHERE name = 'Texas'), 'Lubbock'),
((SELECT id FROM states WHERE name = 'Texas'), 'Orange'),
((SELECT id FROM states WHERE name = 'Texas'), 'Chambers'),
((SELECT id FROM states WHERE name = 'Texas'), 'Liberty'),
((SELECT id FROM states WHERE name = 'Texas'), 'Waller'),
((SELECT id FROM states WHERE name = 'Texas'), 'Bastrop'),
((SELECT id FROM states WHERE name = 'Texas'), 'Caldwell'),
((SELECT id FROM states WHERE name = 'Texas'), 'Comal'),
((SELECT id FROM states WHERE name = 'Texas'), 'Kendall'),
((SELECT id FROM states WHERE name = 'Texas'), 'Bandera'),
((SELECT id FROM states WHERE name = 'Texas'), 'Medina'),
((SELECT id FROM states WHERE name = 'Texas'), 'Uvalde'),
((SELECT id FROM states WHERE name = 'Texas'), 'Kerr'),
((SELECT id FROM states WHERE name = 'Texas'), 'Gillespie'),
((SELECT id FROM states WHERE name = 'Texas'), 'Blanco'),
((SELECT id FROM states WHERE name = 'Texas'), 'Burnet'),
((SELECT id FROM states WHERE name = 'Texas'), 'Llano'),
((SELECT id FROM states WHERE name = 'Texas'), 'Mason'),
((SELECT id FROM states WHERE name = 'Texas'), 'Kimble'),
((SELECT id FROM states WHERE name = 'Texas'), 'Menard');

-- Insert Florida counties (subset)
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'Florida'), 'Miami-Dade'),
((SELECT id FROM states WHERE name = 'Florida'), 'Broward'),
((SELECT id FROM states WHERE name = 'Florida'), 'Palm Beach'),
((SELECT id FROM states WHERE name = 'Florida'), 'Hillsborough'),
((SELECT id FROM states WHERE name = 'Florida'), 'Orange'),
((SELECT id FROM states WHERE name = 'Florida'), 'Pinellas'),
((SELECT id FROM states WHERE name = 'Florida'), 'Duval'),
((SELECT id FROM states WHERE name = 'Florida'), 'Lee'),
((SELECT id FROM states WHERE name = 'Florida'), 'Polk'),
((SELECT id FROM states WHERE name = 'Florida'), 'Volusia'),
((SELECT id FROM states WHERE name = 'Florida'), 'Brevard'),
((SELECT id FROM states WHERE name = 'Florida'), 'Pasco'),
((SELECT id FROM states WHERE name = 'Florida'), 'Seminole'),
((SELECT id FROM states WHERE name = 'Florida'), 'Sarasota'),
((SELECT id FROM states WHERE name = 'Florida'), 'Manatee'),
((SELECT id FROM states WHERE name = 'Florida'), 'Lake'),
((SELECT id FROM states WHERE name = 'Florida'), 'Collier'),
((SELECT id FROM states WHERE name = 'Florida'), 'Leon'),
((SELECT id FROM states WHERE name = 'Florida'), 'Escambia'),
((SELECT id FROM states WHERE name = 'Florida'), 'Clay'),
((SELECT id FROM states WHERE name = 'Florida'), 'St. Johns'),
((SELECT id FROM states WHERE name = 'Florida'), 'Osceola'),
((SELECT id FROM states WHERE name = 'Florida'), 'Marion'),
((SELECT id FROM states WHERE name = 'Florida'), 'Alachua'),
((SELECT id FROM states WHERE name = 'Florida'), 'Martin');

-- Insert New York counties (subset)
INSERT INTO counties (state_id, name) VALUES
((SELECT id FROM states WHERE name = 'New York'), 'Kings'),
((SELECT id FROM states WHERE name = 'New York'), 'Queens'),
((SELECT id FROM states WHERE name = 'New York'), 'New York'),
((SELECT id FROM states WHERE name = 'New York'), 'Suffolk'),
((SELECT id FROM states WHERE name = 'New York'), 'Bronx'),
((SELECT id FROM states WHERE name = 'New York'), 'Nassau'),
((SELECT id FROM states WHERE name = 'New York'), 'Westchester'),
((SELECT id FROM states WHERE name = 'New York'), 'Erie'),
((SELECT id FROM states WHERE name = 'New York'), 'Monroe'),
((SELECT id FROM states WHERE name = 'New York'), 'Richmond'),
((SELECT id FROM states WHERE name = 'New York'), 'Onondaga'),
((SELECT id FROM states WHERE name = 'New York'), 'Orange'),
((SELECT id FROM states WHERE name = 'New York'), 'Rockland'),
((SELECT id FROM states WHERE name = 'New York'), 'Albany'),
((SELECT id FROM states WHERE name = 'New York'), 'Oneida'),
((SELECT id FROM states WHERE name = 'New York'), 'Niagara'),
((SELECT id FROM states WHERE name = 'New York'), 'Dutchess'),
((SELECT id FROM states WHERE name = 'New York'), 'Saratoga'),
((SELECT id FROM states WHERE name = 'New York'), 'Rensselaer'),
((SELECT id FROM states WHERE name = 'New York'), 'Broome'),
((SELECT id FROM states WHERE name = 'New York'), 'Jefferson'),
((SELECT id FROM states WHERE name = 'New York'), 'St. Lawrence'),
((SELECT id FROM states WHERE name = 'New York'), 'Chautauqua'),
((SELECT id FROM states WHERE name = 'New York'), 'Oswego'),
((SELECT id FROM states WHERE name = 'New York'), 'Ontario'),
((SELECT id FROM states WHERE name = 'New York'), 'Washington'),
((SELECT id FROM states WHERE name = 'New York'), 'Ulster'),
((SELECT id FROM states WHERE name = 'New York'), 'Putnam'),
((SELECT id FROM states WHERE name = 'New York'), 'Wayne'),
((SELECT id FROM states WHERE name = 'New York'), 'Cayuga');